### PR TITLE
Revert "Issue #3"

### PR DESCRIPTION
**Pull request by Mycobee**
Reverts josh-everett01/travel_tracker#7

We need to revert this PR and go through the review process.  It seems as though you merged in to master before getting a review. 

This is a big no no, and on the job would get you in to very serious trouble.  Fortunately we are learning :) 

@josh-everett01

### CODE REVIEW

**Comment by Mycobee** [comment]
@josh-everett01 this needs to be reviewed and approved please, then merged

**Comment by josh-everett01** [comment]
Sorry about that. From what I see above you were able to revert? I moved card back to "in review" also

**Comment by Mycobee** [comment]
@josh-everett01 this pull request implements the changes to revert the merge.  This pull request must be reviewed and approved before the revert takes place.  At that point, you can push your branch again and make a new pull request

**Comment by Mycobee** [comment]
i.e. "Rob opened the PR, josh must review and approve, then rob must merge"

Then

"josh opens a new PR with the changes, rob reviews and approves, josh must merge"

**Pull request merged**
